meta_product_name: "DOOG"
meta_title: "DOOG - Sauvez le monde depuis votre canapé"
meta_description: "Devenez bénévole et aidez des associations à réaliser leurs projets grâce à vos compétences techniques."
meta_image: "cover.png" # should exist in `app/assets/images/`
