meta_product_name: "DOOG"
meta_title: "DOOG - Sauvez le monde depuis votre canapé"
meta_description: "Devenez bénévole en travaillant sur des projets long terme!"
meta_image: "cover.png" # should exist in `app/assets/images/`
